//! Parsing of the NSS SSLKEYLOGFILE format
//! (<https://tlswg.org/sslkeylogfile/draft-ietf-tls-keylogfile.html>).
//!
//! Adapted from `~/gitrepos/pcapzip/src/keylog.rs` (see `tls13.rs`'s header comment), trimmed
//! down: tlscap only ever reads a keylog and looks up secrets for decryption -- it never writes
//! one back out, never embeds secrets into an output format, and never prunes entries for closed
//! connections (that's an idle-timeout/FIN-RST concern handled at the connection-eviction layer,
//! not the keylog layer -- see `orchestrator.rs`). So this drops pcapzip's `ConnDebugInfo`/
//! `merge_new_secrets_from`/`secret_entries`/`render`/`insert_secret_entry`, none of which tlscap
//! needs.

use std::collections::HashMap;
use std::fmt;

/// The five TLS secret labels relevant to record decryption: TLS 1.3's four traffic secrets, plus
/// TLS 1.2's single CLIENT_RANDOM (master secret) label.
#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub enum SecretLabel {
    ClientRandom,
    ClientHandshakeTrafficSecret,
    ServerHandshakeTrafficSecret,
    ClientTrafficSecret0,
    ServerTrafficSecret0,
    /// Any other label (e.g. EXPORTER_SECRET, a later CLIENT_TRAFFIC_SECRET_N from a KeyUpdate)
    /// -- parsed but never looked up for decryption.
    Other(String),
}

impl SecretLabel {
    fn parse(s: &str) -> Self {
        match s {
            "CLIENT_RANDOM" => SecretLabel::ClientRandom,
            "CLIENT_HANDSHAKE_TRAFFIC_SECRET" => SecretLabel::ClientHandshakeTrafficSecret,
            "SERVER_HANDSHAKE_TRAFFIC_SECRET" => SecretLabel::ServerHandshakeTrafficSecret,
            "CLIENT_TRAFFIC_SECRET_0" => SecretLabel::ClientTrafficSecret0,
            "SERVER_TRAFFIC_SECRET_0" => SecretLabel::ServerTrafficSecret0,
            other => SecretLabel::Other(other.to_string()),
        }
    }
}

impl fmt::Display for SecretLabel {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SecretLabel::ClientRandom => write!(f, "CLIENT_RANDOM"),
            SecretLabel::ClientHandshakeTrafficSecret => {
                write!(f, "CLIENT_HANDSHAKE_TRAFFIC_SECRET")
            }
            SecretLabel::ServerHandshakeTrafficSecret => {
                write!(f, "SERVER_HANDSHAKE_TRAFFIC_SECRET")
            }
            SecretLabel::ClientTrafficSecret0 => write!(f, "CLIENT_TRAFFIC_SECRET_0"),
            SecretLabel::ServerTrafficSecret0 => write!(f, "SERVER_TRAFFIC_SECRET_0"),
            SecretLabel::Other(s) => write!(f, "{s}"),
        }
    }
}

/// A fully parsed keylog file: an index from client_random -> its secrets, for lookup during
/// decrypt.
#[derive(Clone, Debug, Default)]
pub struct Keylog {
    by_client_random: HashMap<Vec<u8>, HashMap<SecretLabel, Vec<u8>>>,
    /// Total non-comment, non-blank lines seen -- exposed only for logging ("reloaded keylog, N
    /// entries") and tests, not used for lookup.
    pub entry_count: usize,
}

impl Keylog {
    pub fn parse(contents: &str) -> Self {
        let mut by_client_random: HashMap<Vec<u8>, HashMap<SecretLabel, Vec<u8>>> = HashMap::new();
        let mut entry_count = 0;

        for raw_line in contents.lines() {
            let line = raw_line.trim_end_matches(['\r', '\n']);
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            let mut parts = line.split_whitespace();
            let (Some(label_str), Some(random_hex), Some(secret_hex)) =
                (parts.next(), parts.next(), parts.next())
            else {
                continue; // unparseable content line -- ignore rather than error, matches keylog parsers' general leniency
            };
            let (Ok(client_random), Ok(secret)) =
                (hex::decode(random_hex), hex::decode(secret_hex))
            else {
                continue;
            };

            let label = SecretLabel::parse(label_str);
            by_client_random
                .entry(client_random)
                .or_default()
                .insert(label, secret);
            entry_count += 1;
        }

        Keylog {
            by_client_random,
            entry_count,
        }
    }

    /// Looks up a specific secret label for a given TLS client_random.
    pub fn secret_for(&self, client_random: &[u8], label: SecretLabel) -> Option<&[u8]> {
        self.by_client_random
            .get(client_random)?
            .get(&label)
            .map(|v| v.as_slice())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_plain_tls13_entries() {
        let kl = Keylog::parse(
            "# SSL/TLS secrets log file, generated by jSSLKeyLog\r\n\
             SERVER_HANDSHAKE_TRAFFIC_SECRET aabb ccdd\r\n\
             CLIENT_HANDSHAKE_TRAFFIC_SECRET aabb eeff\r\n",
        );
        let random = hex::decode("aabb").unwrap();
        assert_eq!(
            kl.secret_for(&random, SecretLabel::ServerHandshakeTrafficSecret),
            Some(&b"\xcc\xdd"[..])
        );
        assert_eq!(
            kl.secret_for(&random, SecretLabel::ClientHandshakeTrafficSecret),
            Some(&b"\xee\xff"[..])
        );
        assert_eq!(
            kl.secret_for(&random, SecretLabel::ClientTrafficSecret0),
            None
        );
        assert_eq!(kl.entry_count, 2);
    }

    #[test]
    fn parses_jsslkeylog_debug_comments_without_erroring() {
        let kl = Keylog::parse(
            "## 2026-07-08 10:00:00.000: /10.0.0.13:9410->/100.68.218.146:39958\r\n\
             SERVER_HANDSHAKE_TRAFFIC_SECRET aabb ccdd\r\n",
        );
        let random = hex::decode("aabb").unwrap();
        assert_eq!(
            kl.secret_for(&random, SecretLabel::ServerHandshakeTrafficSecret),
            Some(&b"\xcc\xdd"[..])
        );
    }

    #[test]
    fn unparseable_content_line_is_ignored_not_fatal() {
        let kl = Keylog::parse("this is not a valid keylog line at all\r\nCLIENT_RANDOM aa bb\r\n");
        assert_eq!(kl.entry_count, 1);
    }

    #[test]
    fn empty_keylog_has_no_entries() {
        let kl = Keylog::parse("");
        assert_eq!(kl.entry_count, 0);
        assert_eq!(kl.secret_for(b"anything", SecretLabel::ClientRandom), None);
    }
}
